# Site settings
title: Cristian D. Carrión
email: wwwcristiancarrion@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm economics student. Topics on my site include
  my teaching interests, R and LaTeX.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://svmiller.com" # the base hostname & protocol for your site
twitter_username: cristcdc
github_username:  cdcarrion
# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
jobtitle: "Student"
excerpt_separator: "<!--more-->"

# SEO stuff
#google_author:
#google_site_verification:
#bing_webmastertools_id:

plugins_dir:
  - jekyll-sitemap

exclude: ['*.Rmd']
